"""Initial migration

Revision ID: 3a6f8f4a1049
Revises: 
Create Date: 2022-02-11 17:24:03.024530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a6f8f4a1049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('persons',
    sa.Column('PersonID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
